# -*- coding: utf-8 -*-
"""2024-09-04-hello_world.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D-g4QlazO_03GBYo36Zv8ten6jOL3NrX
"""

print("Hello World")

print("유니코드")

print(2.00*10**-1)

print("\"Hello\"")

"""## sine graph"""

import pylab as py

x_deg = py.arange(-180, 180+1,)
x_rad = py.deg2rad(x_deg)
y = py.sin(x_rad)

py.plot(x_deg, y)

py.xlabel('x (deg)')
py.ylabel('sin(x)')
py.grid(True)